from flask_wtf import FlaskForm
from wtforms import FileField, SubmitField, StringField, IntegerField
from wtforms.validators import DataRequired


class BulkUploadForm(FlaskForm):
    excel_file = FileField('Upload Excel File', validators=[DataRequired()])
    submit = SubmitField('Upload')


class AddNewAssetForm(FlaskForm):
    user_emp_id = StringField('emp_id')
    asset_number = StringField('asset_number', validators=[DataRequired()])
    product_category = StringField('product_category', validators=[DataRequired()])
    product_name = StringField('product_name', validators=[DataRequired()])
    model_version = StringField('model_version', validators=[DataRequired()])
    manufacturer = StringField('manufacturer', validators=[DataRequired()])
    asset_status = StringField('asset_status')
    asset_category = StringField('asset_category')
    oem_serial_number = StringField('oem_serial_number', validators=[DataRequired()])
    system_host_name = StringField('system_host_name')
    ip_address = StringField('ip_address')
    oem_asset_warranty = StringField('oem_asset_warranty')
    oem_warranty_expiry_date = StringField('oem_warranty_expiry_date')
    insurance_coverage = StringField('insurance_coverage')
    insurance_company = StringField('insurance_company')
    policy_number = StringField('policy_number')
    insured_amount = IntegerField('insured_amount')
    start_date = StringField('start_date')
    end_date = StringField('end_date')
    supplier_name = StringField('supplier_name')
    supplier_contact = StringField('supplier_contact')
    supplier_location = StringField('supplier_location')
    supplier_email = StringField('supplier_email')
    incident_id = StringField('incident_id')
    remarks = StringField('remarks')
    payment_done = StringField('payment_done')
    payment_date = StringField('payment_date')
    voucher_number = StringField('voucher_number')
    disposal_date = StringField('disposal_date')
    disposal_amount = IntegerField('disposal_amount')
    desk_lap_operating_system = StringField('desk_lap_operating_system')
    desk_lap_hdd_type = StringField('desk_lap_hdd_type')
    desk_lap_hdd_size = IntegerField('desk_lap_hdd_size')
    desk_lap_ram_type = StringField('desk_lap_ram_type')
    desk_lap_ram_size = IntegerField('desk_lap_ram_size')
    desk_lap_ram_frequency = IntegerField('desk_lap_ram_frequency')
    desk_lap_ram_expandable_upto = IntegerField('desk_lap_ram_expandable_upto')
    desk_lap_no_of_ram_slots =  IntegerField('desk_lap_no_of_ram_slots')
    desk_lap_hdmi_port = StringField('desk_lap_hdmi_port')
    desk_lap_display_size = IntegerField('desk_lap_display_size')
    desk_lap_graphics_card_size = IntegerField('desk_lap_graphics_card_size')
    desk_lap_graphics_card_version = StringField('desk_lap_graphics_card_version')
    printer_type = StringField('printer_type')
    printing_type = StringField('printing_type')
    printer_toner_name = StringField('printer_toner_name')
    printer_connectivity = StringField('printer_connectivity')
    hdd_size = IntegerField('hdd_size')
    hdd_type = StringField('hdd_type')
    hdd_connectivity = StringField('hdd_connectivity')
    tab_os = StringField('tab_os')
    tab_storage =  IntegerField('tab_storage')
    tab_ram_size =  IntegerField('tab_ram_size')
    tab_display_size = IntegerField('tab_display_size')
    tab_stylus = StringField('tab_stylus')
    tab_connectivity = StringField('tab_connectivity')
    monitor_display_size = IntegerField('monitor_display_size')
    monitor_hdmi_port = StringField('monitor_hdmi_port')
    monitor_speaker = StringField('monitor_speaker')
    ups_capacity = StringField('ups_capacity')
    ups_amc = StringField('ups_amc')
    ups_start_date = StringField('ups_start_date')
    ups_end_date = StringField('ups_end_date')
    source_of_purchase = StringField('source_of_purchase', validators=[DataRequired()])
    contract_id = StringField('contract_id', validators=[DataRequired()])
    invoice_amount = IntegerField('invoice_amount', validators=[DataRequired()])
    invoice_date = StringField('invoice_date', validators=[DataRequired()])
    invoice_upload = StringField('invoice_upload', validators=[DataRequired()])
    submit = SubmitField('Submit')