"""first migration

Revision ID: 7364f207d2bf
Revises: 
Create Date: 2023-08-11 11:02:40.344250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7364f207d2bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_users',
    sa.Column('user_employee_id', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('user_email', sa.String(length=30), nullable=True),
    sa.Column('user_contact_number', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_employee_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('asset_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_emp_id', sa.String(), nullable=True),
    sa.Column('asset_number', sa.String(length=20), nullable=True),
    sa.Column('product_category', sa.String(length=20), nullable=True),
    sa.Column('product_name', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.String(length=20), nullable=True),
    sa.Column('asset_status', sa.String(length=20), nullable=True),
    sa.Column('asset_category', sa.String(length=20), nullable=True),
    sa.Column('oem_serial_number', sa.String(length=20), nullable=True),
    sa.Column('system_host_name', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=20), nullable=True),
    sa.Column('oem_asset_warranty', sa.String(length=20), nullable=True),
    sa.Column('oem_warranty_expiry_date', sa.String(length=20), nullable=True),
    sa.Column('insurance_coverage', sa.String(length=20), nullable=True),
    sa.Column('insurance_company', sa.String(length=20), nullable=True),
    sa.Column('policy_number', sa.String(length=20), nullable=True),
    sa.Column('insured_amount', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=20), nullable=True),
    sa.Column('supplier_contact', sa.String(length=20), nullable=True),
    sa.Column('supplier_location', sa.String(length=20), nullable=True),
    sa.Column('supplier_email', sa.String(length=20), nullable=True),
    sa.Column('incident_id', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('payment_done', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.String(length=20), nullable=True),
    sa.Column('voucher_number', sa.String(length=20), nullable=True),
    sa.Column('disposal_date', sa.String(length=20), nullable=True),
    sa.Column('disposal_amount', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.String(length=20), nullable=True),
    sa.Column('transfer_amount', sa.Integer(), nullable=True),
    sa.Column('transferred_from', sa.String(length=20), nullable=True),
    sa.Column('transfer_to', sa.String(length=20), nullable=True),
    sa.Column('desk_lap_operating_system', sa.String(length=20), nullable=True),
    sa.Column('desk_lap_hdd_type', sa.String(length=20), nullable=True),
    sa.Column('desk_lap_hdd_size', sa.Integer(), nullable=True),
    sa.Column('desk_lap_ram_type', sa.String(length=20), nullable=True),
    sa.Column('desk_lap_ram_size', sa.Integer(), nullable=True),
    sa.Column('desk_lap_ram_frequency', sa.Integer(), nullable=True),
    sa.Column('desk_lap_ram_expandable_upto', sa.Integer(), nullable=True),
    sa.Column('desk_lap_no_of_ram_slots', sa.Integer(), nullable=True),
    sa.Column('desk_lap_hdmi_port', sa.String(length=20), nullable=True),
    sa.Column('desk_lap_display_size', sa.Integer(), nullable=True),
    sa.Column('desk_lap_graphics_card_size', sa.Integer(), nullable=True),
    sa.Column('desk_lap_graphics_card_version', sa.String(length=20), nullable=True),
    sa.Column('printer_type', sa.String(length=20), nullable=True),
    sa.Column('printing_type', sa.String(length=20), nullable=True),
    sa.Column('printer_toner_name', sa.String(length=20), nullable=True),
    sa.Column('printer_connectivity', sa.String(length=20), nullable=True),
    sa.Column('hdd_size', sa.Integer(), nullable=True),
    sa.Column('hdd_type', sa.String(length=20), nullable=True),
    sa.Column('hdd_connectivity', sa.String(length=20), nullable=True),
    sa.Column('tab_os', sa.String(length=20), nullable=True),
    sa.Column('tab_storage', sa.Integer(), nullable=True),
    sa.Column('tab_ram_size', sa.Integer(), nullable=True),
    sa.Column('tab_display_size', sa.Integer(), nullable=True),
    sa.Column('tab_stylus', sa.String(length=20), nullable=True),
    sa.Column('tab_connectivity', sa.String(length=20), nullable=True),
    sa.Column('monitor_display_size', sa.Integer(), nullable=True),
    sa.Column('monitor_hdmi_port', sa.String(length=20), nullable=True),
    sa.Column('monitor_speaker', sa.String(length=20), nullable=True),
    sa.Column('ups_capacity', sa.String(length=20), nullable=True),
    sa.Column('ups_amc', sa.String(length=20), nullable=True),
    sa.Column('ups_start_date', sa.String(length=20), nullable=True),
    sa.Column('ups_end_date', sa.String(length=20), nullable=True),
    sa.Column('source_of_purchase', sa.String(length=20), nullable=True),
    sa.Column('contract_id', sa.String(length=20), nullable=True),
    sa.Column('invoice_amount', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.String(length=20), nullable=True),
    sa.Column('invoice_upload', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_emp_id'], ['asset_users.user_employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_details')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('asset_users')
    # ### end Alembic commands ###
